---
title: "Instructor Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options:
  chunk_output_type: console
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)
library(shiny)
library(scales)

source('scratch.R')
```


Inputs {.sidebar}
--------------------------------

```{r}

selectInput("section", label = h4("Section"),
            choices = c("All", inClass),
            selected = "All")
```


Column
---------------------------------

### Submissions

```{r}
renderPlot({
  if (input$section == "All") {
    ggplot(submissions, aes(x = chunk, y = percent / 100)) + geom_col(fill = 'steelblue') + 
      scale_y_continuous(name = "", labels = percent) + 
      scale_x_discrete(name = "Chunk Submitted") +
      geom_text(aes(label = round(percent, 2)), vjust = -.3, size = 3.5) + 
      ggtitle("Students that have Submitted a File") +
      theme_minimal()
  }
  else {
    submissions %>% filter(slackDomain == input$section) %>%
      ggplot(aes(x = chunk, y = percent / 100)) + geom_col(fill = 'steelblue') + 
        scale_y_continuous(name = "", labels = percent) + 
        scale_x_discrete(name = "Chunk Submitted") +
        geom_text(aes(label = round(percent, 2)), vjust = -.3, size = 3.5) + 
        ggtitle("Students that have Submitted a File") +
        theme_minimal()
  }
})
```


Column
---------------------------------

### Multiple Submissions

```{r}
ggplot(percMult, aes(x=chunk, y=percent/100)) + geom_col(fill = 'steelblue') +
  scale_y_continuous(name = "", labels = percent) + 
  scale_x_discrete(name = "Chunks Submitted") + 
  geom_text(aes(label=round(percent, 2)), vjust = -.3, size = 3.5) +
  ggtitle("Students that have Re-Submitted a File") + 
  theme_minimal()
```

### Pageviews

```{r}
ggplot(plot, aes(x = a_date, y = n)) + geom_line(aes(color = a_pagePath)) +
  scale_y_continuous(name = "Pageviews") +
  scale_x_date(name = "Date") +
  theme_minimal()
```

