---
title: "Student Dashboard 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(shiny)
library(RColorBrewer)

source('studentBackEnd.R')
```


Inputs {.sidebar}
===================================
```{r}
renderText("Only one student's information will display at a time, so please return the selection to 'Select a Student' before you select a student from another section.")

# Section / Student Dropdown Selection
selectInput("student1", "Section 1", sec1, selected = "NA")
selectInput("student2", "Section 2", sec2, selected = "NA")
selectInput("student3", "Section 3", sec3, selected = "NA")
selectInput("student4", "Section 4", sec4, selected = "NA")
selectInput("student5", "Section 5", sec5, selected = "NA")
selectInput("student6", "Section 6", sec6, selected = "NA")
selectInput("student8", "Section 8", sec8, selected = "NA")

# Big IF
studentID <- reactive({
  if (input$student1 != "NA"){
    input$student1
  }
  else if (input$student2 != "NA"){
    input$student2
  }
  else if (input$student3 != "NA"){
    input$student3
  }
  else if (input$student4 != "NA"){
    input$student4
  }
  else if (input$student5 != "NA"){
    input$student5
  }
  else if (input$student6 != "NA"){
    input$student6
  }
  else {
    input$student8
  }
})
```


Theory
====================================

Pageviews + Time
---------------------------
```{r}
#renderTable({
#  theory2 %>% filter(pawsId == studentID())
#}, bordered = TRUE, striped = TRUE)
```


Practice
================================

```{r}
# Attendance Variables
mLecture <- reactive(as.character(big %>% filter(pawsId == studentID()) %>% 
                                    filter(eventTopic == 'lecture') %>% select(missed)))
mPractice <- reactive(as.character(big %>% filter(pawsId == studentID()) %>% 
                                    filter(eventTopic == 'practice') %>% select(missed)))
pLecture <- reactive(as.double(big %>% filter(pawsId == studentID()) %>% 
                                    filter(eventTopic == 'lecture') %>% select(attPerc)))
pPractice <- reactive(as.double(big %>% filter(pawsId == studentID()) %>% 
                                    filter(eventTopic == 'practice') %>% select(attPerc)))

# Submissions Table
studentSubs <- reactive(filter(subs, pawsId == studentID()) %>% select(label, submissions, bestScore))
```

Attendance
------------------------------

### Lectures Missed of `r lecTotal$classTotal[1]`
```{r}
renderValueBox({valueBox(
  (ifelse(mLecture() == "integer(0)", "All", mLecture())), color = ifelse(
    mLecture() == "integer(0)", "danger", ifelse(
      pLecture() > .5, "primary", ifelse(
        pLecture() < .25, "danger", "warning"))))
  })
```

### Practices Missed of `r pracTotal$classTotal[1]`
```{r}
renderValueBox({valueBox(
  (ifelse(mPractice() == "integer(0)", "All", mPractice())), color = ifelse(
    mPractice() == "integer(0)", "danger", ifelse(
      pPractice() > .5, "primary", ifelse(
        pPractice() < .25, "danger", "warning"))))
  })
```

Submissions
-------------------------------

### Assignments Submitted
```{r}
renderPlot({
  ggplot(studentSubs(), aes(x = label, y = bestScore)) +
    geom_col(fill = "#FF9999") + 
    geom_text(aes(label = submissions), position = position_stack(vjust = .5), size = 10) + 
    theme_minimal() + ylab("Best Score") + xlab("Chunk")
})
```

Skips
------------------------------

### Assignments with No Submissions
```{r}
renderPlot({
  filter(assignments, !(chunkId %in% studentSubs()$label)) %>% arrange(chunkId) %>%
    ggplot(aes(x = st2, fill = mainTopic)) + geom_bar() + xlab("Topic") + 
    ylab("Assignments Left") + theme_minimal() + 
    scale_fill_manual(values = brewer.pal(3, "Accent"))
})
```

