---
title: "studentDash"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(shiny)

source('studentBackEnd.R')
```

Inputs {.sidebar}
------------------------------
```{r}
# inputs
radioButtons("student", "Select a Student", nameList)
```

```{r}
# Attendance Variables
mLecture <- reactive(as.character(big %>% filter(pawsId == input$student) %>% 
                                    filter(eventTopic == 'lecture') %>% select(missed)))
mPractice <- reactive(as.character(big %>% filter(pawsId == input$student) %>% 
                                    filter(eventTopic == 'practice') %>% select(missed)))
pLecture <- reactive(as.double(big %>% filter(pawsId == input$student) %>% 
                                    filter(eventTopic == 'lecture') %>% select(attPerc)))
pPractice <- reactive(as.double(big %>% filter(pawsId == input$student) %>% 
                                    filter(eventTopic == 'practice') %>% select(attPerc)))

# Submissions Table
studentSubs <- reactive(filter(subs, pawsId == input$student) %>% select(label, submissions, bestScore))
```


Attendance
------------------------------

### Lectures Missed
```{r}
renderValueBox({valueBox(
  (ifelse(mLecture() == "integer(0)", "All", mLecture())), color = ifelse(
    mLecture() == "integer(0)", "danger", ifelse(
      pLecture() > .5, "primary", ifelse(
        pLecture() < .25, "danger", "warning"))))
  })
```

### Practices Missed
```{r}
renderValueBox({valueBox(
  (ifelse(mPractice() == "integer(0)", "All", mPractice())), color = ifelse(
    mPractice() == "integer(0)", "danger", ifelse(
      pPractice() > .5, "primary", ifelse(
        pPractice() < .25, "danger", "warning"))))
  })
```


Submissions
-------------------------------

### Assignments Submitted
```{r}
renderTable({studentSubs()}, bordered = TRUE, striped = TRUE, digits = 0)
```

### Assignments Skipped
```{r}
renderTable({
  filter(assignments, !(chunkId %in% studentSubs()$label)) %>% select(chunkId, subTopic)
}, bordered = TRUE, striped = TRUE)
```

