---
title: "Outbound Links Analysis"
author: "Isabella Hundley"
date: "October 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(knitr)
library(lubridate)

source('scratchDatabase.R')
```

```{r}
outboundLinks <- outboundLinks %>% 
  mutate(domain = case_when(
    grepl('wikipedia.org', a_eventLabel) ~ "wikipedia",
    grepl('support.office.com', a_eventLabel) ~ "support.office",
    grepl('lynda.com', a_eventLabel) ~ "lynda",
    TRUE ~ "other"
  ))


outboundLinks$a_timestamp <- outboundLinks$a_timestamp / 1000
outboundLinks$a_timestamp <- as.POSIXct(outboundLinks$a_timestamp,origin = "1970-01-01", tz = "America/Chicago")
outboundLinks <- outboundLinks %>% filter(a_timestamp > as.Date("2018-08-20 7:00:00")) %>% mutate(date = date(a_timestamp))
```

Outbound Link Domains
```{r}
outboundLinks %>% group_by(domain) %>% summarise(clicks = sum(n)) %>% arrange(desc(clicks)) %>%
  kable()
```


```{r}
outboundLinks %>% group_by(domain, date) %>% summarise(clicks = sum(n)) %>%
  filter(domain != 'slack') %>%
  ggplot(aes(x = date, y = clicks, color = domain)) + geom_line() +
  theme_minimal() + ggtitle("Clicks per Day", subtitle = "without slack") +
  labs(y = "Clicks", x = "Date")
```


```{r}
outboundLinks %>% group_by(domain, date) %>% summarise(clicks = sum(n)) %>%
  filter(domain != 'slack', domain != 'support.office') %>%
  ggplot(aes(x = date, y = clicks, color = domain)) + geom_line() +
  theme_minimal() + ggtitle("Clicks per Day", subtitle = "without slack and support.office") +
  labs(y = "Clicks", x = "Date")
```

